In [41]:
import pandas as pd

df1=pd.read_csv("/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/EGLL_2023-04-01_00-00_till_2023-08-31_23-30.csv")
df2=pd.read_csv("/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/EGLL_2023-08-29_00-00_till_2023-09-15_23-30.csv")
df3=pd.read_csv("/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/EGLL_2023-09-16_00-00_till_2023-09-30_23-30.csv")
df4=pd.read_csv("/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/EGLL_2023-10-01_00-00_till_2023-10-15_23-30.csv")
df5=pd.read_csv("/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/EGLL_2023-10-16_00-00_till_2023-10-31_23-30.csv")
df6=pd.read_csv("/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/EGLL_2023-11-01_00-00_till_2023-11-15_23-30.csv")
df7=pd.read_csv("/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/EGLL_2023-11-16_00-00_till_2023-11-30_23-30.csv")
df8=pd.read_csv("/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/EGLL_2023-12-01_00-00_till_2023-12-15_23-30.csv")
df9=pd.read_csv("/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/EGLL_2023-12-16_00-00_till_2023-12-31_23-30.csv")
df10=pd.read_csv("/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/EGLL_2024-01-01_00-00_till_2024-01-15_23-30.csv")
df11=pd.read_csv("/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/EGLL_2024-01-16_00-00_till_2024-01-31_23-30.csv")
df12=pd.read_csv("/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/EGLL_2024-02-01_00-00_till_2024-02-15_23-30.csv")
df13=pd.read_csv("/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/EGLL_2024-02-16_00-00_till_2024-02-29_23-30.csv")
df14=pd.read_csv("/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/EGLL_2024-03-01_00-00_till_2024-03-15_23-30.csv")
df15=pd.read_csv("/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/EGLL_2024-03-16_00-00_till_2024-03-31_23-30.csv")



#df6=pd.read_csv("EGLL_2023-06-1_00-00_till_2023-06-15_23-30.csv")
#df7=pd.read_csv("EGLL_2023-05-16_00-00_till_2023-05-31_23-30.csv")
#df8=pd.read_csv("EGLL_2023-05-1_00-00_till_2023-05-15_23-30.csv")
#df9=pd.read_csv("EGLL_2023-04-15_00-00_till_2023-04-30_23-30.csv")
#df10=pd.read_csv("EGLL_2023-04-01_00-00_till_2023-04-14_23-30.csv")

In [42]:
df1.tail()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Flight Number,Holding Time (minutes),Type Code,Time over fix,Big,Ock,Bov,...,Altitude at -60,Departures delayIndex at -0,Arrivals numCancelled at -0,Arrivals delayIndex at -0,Departures delayIndex at -30,Arrivals numCancelled at -30,Arrivals delayIndex at -30,Departures delayIndex at -60,Arrivals numCancelled at -60,Arrivals delayIndex at -60
93815,78950,5224.0,5224,SWR10GD _3608,0.0,BCS1,NaN,0,0,0,...,0.0,2.06,14.0,0.56,2.28,11.0,0.56,2.19,8.0,0.0
93816,78951,5225.0,5225,MSR777 _007,0.0,B77W,NaN,0,0,0,...,37000.0,2.06,14.0,0.56,2.28,11.0,0.56,2.19,8.0,0.0
93817,78952,5226.0,5226,BAW9253 _732,0.0,A319,2023-08-29 11:56:29,0,0,1,...,0.0,2.06,14.0,0.56,2.28,11.0,0.56,2.19,8.0,0.0
93818,78953,5227.0,5227,BAW343E _2632,0.0,A20N,NaN,0,0,0,...,28000.0,2.06,14.0,0.56,2.28,11.0,0.56,2.19,8.0,0.0
93819,78954,5228.0,5228,SAS531 _3869,0.0,A20N,NaN,0,0,0,...,39000.0,2.06,14.0,0.56,2.28,11.0,0.56,2.19,8.0,0.0

In [43]:
df2.head()

,Unnamed: 0,Flight Number,Holding Time (minutes),Type Code,Time over fix,Big,Ock,Bov,Lam,WTC L,...,Altitude at -60,Departures delayIndex at -0,Arrivals numCancelled at -0,Arrivals delayIndex at -0,Departures delayIndex at -30,Arrivals numCancelled at -30,Arrivals delayIndex at -30,Departures delayIndex at -60,Arrivals numCancelled at -60,Arrivals delayIndex at -60
0,0,BAW16 _5505,0.0,B789,2023-08-29 03:43:29,0,0,0,1,0.0,...,41000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,QFA9 _10043,0.0,B789,2023-08-29 03:45:29,0,0,0,1,0.0,...,41000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,BAW262 _1319,0.0,B772,2023-08-29 03:53:59,0,0,0,1,0.0,...,41000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,BAW106 _6977,0.0,B78X,2023-08-29 04:09:29,0,0,0,1,0.0,...,37000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,BAW74 _5102,0.0,B77W,2023-08-29 04:15:59,1,0,0,0,0.0,...,37000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [44]:
# Specify the cutoff date
cutoff_date = '2023-08-29'

# Filter rows to exclude the ones from the cutoff date onwards
df1 = df1[df1['TimeStamp'] < cutoff_date]

print(df1)

       Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  Flight Number  \
0                 0       70378.0           0  VIR450  _4170
1                 1       70379.0           1  BAW074  _2949
2                 2       70380.0           2  BAW124  _1015
3                 3       70381.0           3  CPA251  _7192
4                 4       70382.0           4  BAW58L  _1080
...             ...           ...         ...            ...
93536         78671        4945.0        4945  THY9YU  _3719
93537         78672        4946.0        4946  LOT285  _3513
93538         78673        4947.0        4947  BAW327X _1328
93539         78674        4948.0        4948  BAW73V  _1706
93540         78675        4949.0        4949  BAW689  _2500

       Holding Time (minutes) Type Code        Time over fix  Big  Ock  Bov  \
0                         0.0      B789  2023-04-01 03:31:29    1    0    0
1                         0.0      B77W  2023-04-01 03:58:29    0    1    0
2                         0.0      B772  2023-04-01 04:08:59    0    0    0
3                         0.0      B77W  2023-04-01 04:11:29    0    0    0
4                         0.0      B772  2023-04-01 04:22:29    1    0    0
...                       ...       ...                  ...  ...  ...  ...
93536                     0.0      A21N                  NaN    0    0    0
93537                     0.0      B38M                  NaN    0    0    0
93538                     0.0      A321  2023-08-28 23:07:59    1    0    0
93539                     0.0      A320  2023-08-28 23:17:29    1    0    0
93540                     0.0      A20N                  NaN    0    0    0

       ...  Altitude at -60  Departures delayIndex at -0  \
0      ...          40000.0                         0.00
1      ...          36000.0                         0.00
2      ...          39000.0                         0.00
3      ...          35000.0                         0.00
4      ...          38000.0                         0.00
...    ...              ...                          ...
93536  ...          35000.0                         2.44
93537  ...          39000.0                         2.44
93538  ...              0.0                         2.44
93539  ...              0.0                         2.44
93540  ...          39000.0                         2.44

       Arrivals numCancelled at -0  Arrivals delayIndex at -0  \
0                              0.0                        0.0
1                              0.0                        0.0
2                              0.0                        0.0
3                              0.0                        0.0
4                              0.0                        0.0
...                            ...                        ...
93536                         22.0                        5.0
93537                         22.0                        5.0
93538                         21.0                        5.0
93539                         12.0                        5.0
93540                         10.0                        5.0

       Departures delayIndex at -30  Arrivals numCancelled at -30  \
0                              0.00                           0.0
1                              0.00                           0.0
2                              0.00                           0.0
3                              0.00                           0.0
4                              0.00                           0.0
...                             ...                           ...
93536                          2.44                          33.0
93537                          2.44                          33.0
93538                          2.39                          29.0
93539                          2.44                          22.0
93540                          2.44                          21.0

       Arrivals delayIndex at -30 Departures delayIndex at -60  \
0                             0.0                         0.00
1                             0.0                         0.00
2                             0.0                         0.00
3                             0.0                         0.00
4                             0.0                         0.00
...                           ...                          ...
93536                         5.0                         4.64
93537                         5.0                         4.64
93538                         5.0                         4.14
93539                         5.0                         4.00
93540                         5.0                         3.11

       Arrivals numCancelled at -60  Arrivals delayIndex at -60
0                               0.0                         0.0
1                               0.0                         0.0
2                               0.0                         0.0
3                               0.0                         0.0
4                               0.0                         0.0
...                             ...                         ...
93536                          37.0                         5.0
93537                          37.0                         5.0
93538                          36.0                         5.0
93539                          37.0                         5.0
93540                          39.0                         5.0

[93541 rows x 93 columns]

In [45]:
# Drop unnamed columns
df1 = df1.loc[:, ~df1.columns.str.contains('^Unnamed')]
# Drop unnamed columns
df2 = df2.loc[:, ~df2.columns.str.contains('^Unnamed')]
# Drop unnamed columns
df3 = df3.loc[:, ~df3.columns.str.contains('^Unnamed')]
# Drop unnamed columns
df4 = df4.loc[:, ~df4.columns.str.contains('^Unnamed')]
# Drop unnamed columns
df5 = df5.loc[:, ~df5.columns.str.contains('^Unnamed')]
# Drop unnamed columns
df6 = df6.loc[:, ~df6.columns.str.contains('^Unnamed')]
# Drop unnamed columns
df7 = df7.loc[:, ~df7.columns.str.contains('^Unnamed')]
# Drop unnamed columns
df8 = df8.loc[:, ~df8.columns.str.contains('^Unnamed')]
# Drop unnamed columns
df9 = df9.loc[:, ~df9.columns.str.contains('^Unnamed')]
# Drop unnamed columns
df10 = df10.loc[:, ~df10.columns.str.contains('^Unnamed')]
# Drop unnamed columns
df11 = df11.loc[:, ~df11.columns.str.contains('^Unnamed')]
# Drop unnamed columns
df12 = df12.loc[:, ~df12.columns.str.contains('^Unnamed')]
# Drop unnamed columns
df13 = df13.loc[:, ~df13.columns.str.contains('^Unnamed')]
# Drop unnamed columns
df14 = df14.loc[:, ~df14.columns.str.contains('^Unnamed')]
# Drop unnamed columns
df15 = df15.loc[:, ~df15.columns.str.contains('^Unnamed')]

In [46]:
frames = [df1, df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15]
df_full = pd.concat(frames,ignore_index=True)
df_full = df_full.sort_values(by='TimeStamp')
df_full

,Flight Number,Holding Time (minutes),Type Code,Time over fix,Big,Ock,Bov,Lam,WTC L,WTC M,...,Altitude at -60,Departures delayIndex at -0,Arrivals numCancelled at -0,Arrivals delayIndex at -0,Departures delayIndex at -30,Arrivals numCancelled at -30,Arrivals delayIndex at -30,Departures delayIndex at -60,Arrivals numCancelled at -60,Arrivals delayIndex at -60
0,VIR450 _4170,0.0,B789,2023-04-01 03:31:29,1,0,0,0,0.0,0.0,...,40000.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0
1,BAW074 _2949,0.0,B77W,2023-04-01 03:58:29,0,1,0,0,0.0,0.0,...,36000.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0
2,BAW124 _1015,0.0,B772,2023-04-01 04:08:59,0,0,0,1,0.0,0.0,...,39000.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0
3,CPA251 _7192,0.0,B77W,2023-04-01 04:11:29,0,0,0,1,0.0,0.0,...,35000.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0
4,BAW58L _1080,0.0,B772,2023-04-01 04:22:29,1,0,0,0,0.0,0.0,...,38000.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222976,BAW49TA _2662,6.5,A320,2024-03-31 21:23:59,0,0,1,0,0.0,1.0,...,33000.0,1.33,0.0,0.0,1.50,1.0,0.0,1.67,1.0,0.0
222977,BAW64VC _2697,7.0,A319,2024-03-31 21:26:59,0,0,1,0,0.0,1.0,...,38000.0,1.33,0.0,0.0,1.50,1.0,0.0,1.67,1.0,0.0
222978,BAW597C _2185,5.0,A320,2024-03-31 21:35:29,0,0,1,0,0.0,1.0,...,38000.0,1.17,0.0,0.0,1.44,1.0,0.0,1.61,1.0,0.0
222979,BAW900A _2227,4.5,A320,2024-03-31 21:31:59,0,0,1,0,0.0,1.0,...,37000.0,1.17,0.0,0.0,1.44,1.0,0.0,1.61,1.0,0.0
222980,TAP66JC _7201,5.0,A320,2024-03-31 21:42:59,0,0,1,0,0.0,1.0,...,37000.0,1.11,0.0,0.0,1.33,0.0,0.0,1.56,1.0,0.0

In [95]:
cleaned_data.to_csv('/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/EGLL_2023-04-01_00-00_till_2024-03-31_23-30_cleaned.csv')

In [93]:
df_full

# Remove the row by index number
cleaned_data = df_full.drop(index=189217)
cleaned_data = cleaned_data.drop(index=189292)
cleaned_data = cleaned_data.drop(index=142225)
cleaned_data = cleaned_data.drop(index=153374)
cleaned_data = cleaned_data.drop(index=148199)
cleaned_data = cleaned_data.drop(index=122012)

In [94]:
cleaned_data=cleaned_data.sort_values(by='Holding Time (minutes)')
cleaned_data

,Flight Number,Holding Time (minutes),Type Code,Time over fix,Big,Ock,Bov,Lam,WTC L,WTC M,...,Altitude at -60,Departures delayIndex at -0,Arrivals numCancelled at -0,Arrivals delayIndex at -0,Departures delayIndex at -30,Arrivals numCancelled at -30,Arrivals delayIndex at -30,Departures delayIndex at -60,Arrivals numCancelled at -60,Arrivals delayIndex at -60
0,VIR450 _4170,0.0,B789,2023-04-01 03:31:29,1,0,0,0,0.0,0.0,...,40000.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00
118212,SHT7B _2891,0.0,A320,2023-10-06 13:18:29,0,0,1,0,0.0,1.0,...,0.0,1.50,1.0,0.00,1.50,3.0,0.00,1.39,4.0,0.00
118210,BAW6B _2728,0.0,A388,2023-10-06 13:14:29,0,0,1,0,0.0,0.0,...,40000.0,1.50,3.0,0.00,1.50,3.0,0.00,1.44,4.0,0.00
118208,BAW80KA _3801,0.0,A21N,2023-10-06 13:10:59,0,0,1,0,0.0,1.0,...,38000.0,1.50,3.0,0.00,1.50,3.0,0.00,1.44,4.0,0.00
118207,BAW311 _1730,0.0,A320,2023-10-06 13:13:59,0,1,0,0,0.0,1.0,...,38000.0,1.50,3.0,0.00,1.50,3.0,0.00,1.44,4.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189629,BAW9EW _4148,42.5,B789,2024-02-08 07:59:59,0,0,1,0,0.0,0.0,...,40000.0,0.89,0.0,0.28,0.89,0.0,0.03,0.00,0.0,0.00
189660,EIN154 _6999,43.0,A21N,2024-02-08 08:54:59,0,0,1,0,0.0,1.0,...,0.0,0.94,1.0,1.00,0.94,1.0,0.56,0.89,0.0,0.03
189641,VIR198 _3567,44.0,A333,2024-02-08 08:20:29,0,1,0,0,0.0,0.0,...,40000.0,0.94,1.0,0.56,0.89,0.0,0.28,0.69,0.0,0.00
131120,AAL20 _9172,45.0,B77W,2023-10-31 05:01:29,0,1,0,0,0.0,0.0,...,34000.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00
200163,SVA119 _7292,70.0,B77W,2024-02-25 05:50:59,0,0,0,1,0.0,0.0,...,35000.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00

In [85]:
df_full

,Flight Number,Holding Time (minutes),Type Code,Time over fix,Big,Ock,Bov,Lam,WTC L,WTC M,...,Altitude at -60,Departures delayIndex at -0,Arrivals numCancelled at -0,Arrivals delayIndex at -0,Departures delayIndex at -30,Arrivals numCancelled at -30,Arrivals delayIndex at -30,Departures delayIndex at -60,Arrivals numCancelled at -60,Arrivals delayIndex at -60
0,VIR450 _4170,0.0,B789,2023-04-01 03:31:29,1,0,0,0,0.0,0.0,...,40000.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0
1,BAW074 _2949,0.0,B77W,2023-04-01 03:58:29,0,1,0,0,0.0,0.0,...,36000.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0
2,BAW124 _1015,0.0,B772,2023-04-01 04:08:59,0,0,0,1,0.0,0.0,...,39000.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0
3,CPA251 _7192,0.0,B77W,2023-04-01 04:11:29,0,0,0,1,0.0,0.0,...,35000.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0
4,BAW58L _1080,0.0,B772,2023-04-01 04:22:29,1,0,0,0,0.0,0.0,...,38000.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222976,BAW49TA _2662,6.5,A320,2024-03-31 21:23:59,0,0,1,0,0.0,1.0,...,33000.0,1.33,0.0,0.0,1.50,1.0,0.0,1.67,1.0,0.0
222977,BAW64VC _2697,7.0,A319,2024-03-31 21:26:59,0,0,1,0,0.0,1.0,...,38000.0,1.33,0.0,0.0,1.50,1.0,0.0,1.67,1.0,0.0
222978,BAW597C _2185,5.0,A320,2024-03-31 21:35:29,0,0,1,0,0.0,1.0,...,38000.0,1.17,0.0,0.0,1.44,1.0,0.0,1.61,1.0,0.0
222979,BAW900A _2227,4.5,A320,2024-03-31 21:31:59,0,0,1,0,0.0,1.0,...,37000.0,1.17,0.0,0.0,1.44,1.0,0.0,1.61,1.0,0.0
222980,TAP66JC _7201,5.0,A320,2024-03-31 21:42:59,0,0,1,0,0.0,1.0,...,37000.0,1.11,0.0,0.0,1.33,0.0,0.0,1.56,1.0,0.0

In [12]:
import pandas as pd
df1=pd.read_csv("/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/Delayindex_of_EGLL_from_2023-03-25_01_00_till_2024-03-23_23_30")

In [13]:
df2=pd.read_csv("/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/Delayindex_of_EGLL_from_2024-03-24_00_00_till_2024-04-01_23_30")

In [14]:
# Drop unnamed columns
df1 = df1.loc[:, ~df1.columns.str.contains('^Unnamed')]
# Drop unnamed columns
df2 = df2.loc[:, ~df2.columns.str.contains('^Unnamed')]

In [15]:
df1

,airportIcao,from_utc,to_utc,departures_numTotal,departures_numCancelled,departures_medianDelay,departures_delayIndex,arrivals_numTotal,arrivals_numCancelled,arrivals_medianDelay,arrivals_delayIndex
0,EGLL,2023-03-24 22:00Z,2023-03-25 00:00Z,40,0,00:34:00,1.92,30,2,00:44:00,2.61
1,EGLL,2023-03-24 22:15Z,2023-03-25 00:15Z,35,0,00:36:00,2.00,24,2,00:56:00,3.78
2,EGLL,2023-03-24 22:30Z,2023-03-25 00:30Z,26,0,00:37:00,2.08,15,0,01:17:00,4.28
3,EGLL,2023-03-24 22:45Z,2023-03-25 00:45Z,15,0,00:33:00,1.83,9,0,01:17:00,4.28
4,EGLL,2023-03-24 23:00Z,2023-03-25 01:00Z,9,0,00:45:00,2.50,3,0,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...
35035,EGLL,2024-03-23 20:45Z,2024-03-23 22:45Z,44,0,00:16:00,0.89,26,0,-00:05:00,0.00
35036,EGLL,2024-03-23 21:00Z,2024-03-23 23:00Z,40,0,00:15:00,0.86,20,0,-00:04:00,0.00
35037,EGLL,2024-03-23 21:15Z,2024-03-23 23:15Z,35,0,00:16:00,0.89,17,0,-00:05:00,0.00
35038,EGLL,2024-03-23 21:30Z,2024-03-23 23:30Z,31,0,00:17:00,0.94,14,0,-00:01:00,0.00
35039,EGLL,2024-03-23 21:45Z,2024-03-23 23:45Z,26,0,00:16:00,0.89,10,0,00:10:00,0.56

In [16]:
df2

,airportIcao,from_utc,to_utc,departures_numTotal,departures_numCancelled,departures_medianDelay,departures_delayIndex,arrivals_numTotal,arrivals_numCancelled,arrivals_medianDelay,arrivals_delayIndex
0,EGLL,2024-03-23 22:00Z,2024-03-24 00:00Z,20,0,00:17:00,0.94,6,0,00:12:00,0.67
1,EGLL,2024-03-23 22:15Z,2024-03-24 00:15Z,17,0,00:17:00,0.94,4,0,NaN,0.00
2,EGLL,2024-03-23 22:30Z,2024-03-24 00:30Z,11,0,00:17:00,0.94,3,0,NaN,0.00
3,EGLL,2024-03-23 22:45Z,2024-03-24 00:45Z,3,0,0,0.00,1,0,NaN,0.00
4,EGLL,2024-03-23 23:00Z,2024-03-24 01:00Z,1,0,0,0.00,1,0,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...
855,EGLL,2024-04-01 19:45Z,2024-04-01 21:45Z,67,0,00:18:00,1.00,64,0,-00:07:00,0.00
856,EGLL,2024-04-01 20:00Z,2024-04-01 22:00Z,63,0,00:20:00,1.11,56,0,-00:08:00,0.00
857,EGLL,2024-04-01 20:15Z,2024-04-01 22:15Z,57,0,00:22:00,1.22,51,0,-00:04:00,0.00
858,EGLL,2024-04-01 20:30Z,2024-04-01 22:30Z,48,0,00:20:00,1.11,43,0,00:00:00,0.00
859,EGLL,2024-04-01 20:45Z,2024-04-01 22:45Z,41,0,00:21:00,1.17,36,0,00:01:00,0.08

In [27]:
frames = [df1,df2]
df_full_delay = pd.concat(frames,ignore_index=True)
df_full_delay = df_full_delay.sort_values(by='from_utc')
df_full_delay.drop_duplicates(inplace=True)

In [28]:
df_full_delay

,airportIcao,from_utc,to_utc,departures_numTotal,departures_numCancelled,departures_medianDelay,departures_delayIndex,arrivals_numTotal,arrivals_numCancelled,arrivals_medianDelay,arrivals_delayIndex
0,EGLL,2023-03-24 22:00Z,2023-03-25 00:00Z,40,0,00:34:00,1.92,30,2,00:44:00,2.61
1,EGLL,2023-03-24 22:15Z,2023-03-25 00:15Z,35,0,00:36:00,2.00,24,2,00:56:00,3.78
2,EGLL,2023-03-24 22:30Z,2023-03-25 00:30Z,26,0,00:37:00,2.08,15,0,01:17:00,4.28
3,EGLL,2023-03-24 22:45Z,2023-03-25 00:45Z,15,0,00:33:00,1.83,9,0,01:17:00,4.28
4,EGLL,2023-03-24 23:00Z,2023-03-25 01:00Z,9,0,00:45:00,2.50,3,0,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...
35895,EGLL,2024-04-01 19:45Z,2024-04-01 21:45Z,67,0,00:18:00,1.00,64,0,-00:07:00,0.00
35896,EGLL,2024-04-01 20:00Z,2024-04-01 22:00Z,63,0,00:20:00,1.11,56,0,-00:08:00,0.00
35897,EGLL,2024-04-01 20:15Z,2024-04-01 22:15Z,57,0,00:22:00,1.22,51,0,-00:04:00,0.00
35898,EGLL,2024-04-01 20:30Z,2024-04-01 22:30Z,48,0,00:20:00,1.11,43,0,00:00:00,0.00
35899,EGLL,2024-04-01 20:45Z,2024-04-01 22:45Z,41,0,00:21:00,1.17,36,0,00:01:00,0.08

In [30]:
df_full_delay.to_csv('/Users/elenavella/Library/CloudStorage/OneDrive-Personal/masters/Datasets_full/Dataset_full_year/Delayindex_of_EGLL_from_2023-03-25_01_00_till_2024-04-01_23_30')

In [54]:
import pandas as pd

df=pd.read_csv("EGLL_2023-04-01_00-00_till_2024-03-31_23-30_cleaned.csv")
df

,Unnamed: 0,Flight Number,Holding Time (minutes),Type Code,Time over fix,Big,Ock,Bov,Lam,WTC L,...,Altitude at -60,Departures delayIndex at -0,Arrivals numCancelled at -0,Arrivals delayIndex at -0,Departures delayIndex at -30,Arrivals numCancelled at -30,Arrivals delayIndex at -30,Departures delayIndex at -60,Arrivals numCancelled at -60,Arrivals delayIndex at -60
0,0,VIR450 _4170,0.0,B789,2023-04-01 03:31:29,1,0,0,0,0.0,...,40000.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00
1,118212,SHT7B _2891,0.0,A320,2023-10-06 13:18:29,0,0,1,0,0.0,...,0.0,1.50,1.0,0.00,1.50,3.0,0.00,1.39,4.0,0.00
2,118210,BAW6B _2728,0.0,A388,2023-10-06 13:14:29,0,0,1,0,0.0,...,40000.0,1.50,3.0,0.00,1.50,3.0,0.00,1.44,4.0,0.00
3,118208,BAW80KA _3801,0.0,A21N,2023-10-06 13:10:59,0,0,1,0,0.0,...,38000.0,1.50,3.0,0.00,1.50,3.0,0.00,1.44,4.0,0.00
4,118207,BAW311 _1730,0.0,A320,2023-10-06 13:13:59,0,1,0,0,0.0,...,38000.0,1.50,3.0,0.00,1.50,3.0,0.00,1.44,4.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222970,189629,BAW9EW _4148,42.5,B789,2024-02-08 07:59:59,0,0,1,0,0.0,...,40000.0,0.89,0.0,0.28,0.89,0.0,0.03,0.00,0.0,0.00
222971,189660,EIN154 _6999,43.0,A21N,2024-02-08 08:54:59,0,0,1,0,0.0,...,0.0,0.94,1.0,1.00,0.94,1.0,0.56,0.89,0.0,0.03
222972,189641,VIR198 _3567,44.0,A333,2024-02-08 08:20:29,0,1,0,0,0.0,...,40000.0,0.94,1.0,0.56,0.89,0.0,0.28,0.69,0.0,0.00
222973,131120,AAL20 _9172,45.0,B77W,2023-10-31 05:01:29,0,1,0,0,0.0,...,34000.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00
222974,200163,SVA119 _7292,70.0,B77W,2024-02-25 05:50:59,0,0,0,1,0.0,...,35000.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00

In [55]:
unique_type_codes = df["Type Code"].unique()
print(unique_type_codes)

['B789' 'A320' 'A388' 'A21N' 'B77W' 'B38M' 'B772' 'A339' 'A20N' 'B764'
 'B77L' 'A333' 'A319' nan 'A359' 'A35K' 'B788' 'E55P' 'A321' 'A332' 'B763'
 'E295' 'B738' 'A306' 'E190' 'AT45' 'B78X' 'B737' 'B748' 'B744' 'AT76'
 'BCS3' 'A318' 'E195' 'BCS1' 'S76' 'B752' 'PC12' 'B773' 'A139' 'C56X'
 'B753' 'A169' 'CL35' 'C68A' 'EC35' 'GLF6' 'E145' 'AN2' 'C25M' 'A109'
 'GL7T' 'E75L' 'B39M' 'GA5C' 'B739' 'GLEX' 'EC45' 'A19N' 'A338' 'E35L'
 'AS55' 'A346' 'FA7X' 'LJ60' 'FA8X' 'GL5T' 'GA6C' 'A342' 'B762' 'EC20'
 'E170' 'AT46' 'GLF5' 'E290' 'SF25' 'DH8D' 'F2TH' 'CRJ9' 'A343' 'CL60'
 'R22' 'A119' 'CRJ2' 'H47' 'R66' 'G200' 'AS50' 'R44' 'EC55' 'LJ75' 'C680'
 'GLF4' 'E550' 'HA4T' 'A400' 'S92' 'A345' 'LJ40' 'C17' 'C25C']

In [56]:
counts = df["Type Code"].value_counts()
print(counts)
counts.to_csv('counts')

Type Code
A320    47437
A20N    31447
A319    22813
B789    17252
B77W    15864
        ...
H47         1
A19N        1
A346        1
PC12        1
C25C        1
Name: count, Length: 100, dtype: int64

In [57]:
num_none = df["Type Code"].isna().sum()
print(num_none)

9187

In [58]:
import requests
import json

doc8643_url = r = "https://www4.icao.int/doc8643/External/AircraftTypes"
r = requests.post(doc8643_url)
doc8643at = pd.json_normalize(r.json())
doc8643at.columns = doc8643at.columns.str.lower()
doc8643at = doc8643at.rename(columns={
    "modelfullname": "model",
    "manufacturercode": "manufacturer_code",
    "aircraftdescription": "aircraft_description",
    "enginecount": "engine_count",
    "enginetype": "engine_type",
    "wtg":"RECAT_EU"
    })

def Icao_doc8643(df):
    for index,row in df.iterrows():
        type_code=None
        RECAT_EU=None
        type_code=row['Type Code']

        if pd.notna(row['Type Code']):
            icao_row = doc8643at[doc8643at['designator'] == type_code].iloc[0]
            RECAT_EU=icao_row["RECAT_EU"]

        if RECAT_EU=='A':
            df.at[index,'RECAT_EU_A']=1
            df.at[index,'RECAT_EU_B']=0
            df.at[index,'RECAT_EU_C']=0
            df.at[index,'RECAT_EU_D']=0
            df.at[index,'RECAT_EU_E']=0
            df.at[index,'RECAT_EU_F']=0
            df.at[index,'RECAT_EU_G']=0


        elif RECAT_EU=='B':
            df.at[index,'RECAT_EU_A']=0
            df.at[index,'RECAT_EU_B']=1
            df.at[index,'RECAT_EU_C']=0
            df.at[index,'RECAT_EU_D']=0
            df.at[index,'RECAT_EU_E']=0
            df.at[index,'RECAT_EU_F']=0
            df.at[index,'RECAT_EU_G']=0


        elif RECAT_EU=='C':
            df.at[index,'RECAT_EU_A']=0
            df.at[index,'RECAT_EU_B']=0
            df.at[index,'RECAT_EU_C']=1
            df.at[index,'RECAT_EU_D']=0
            df.at[index,'RECAT_EU_E']=0
            df.at[index,'RECAT_EU_F']=0
            df.at[index,'RECAT_EU_G']=0


        elif RECAT_EU=='D':
            df.at[index,'RECAT_EU_A']=0
            df.at[index,'RECAT_EU_B']=0
            df.at[index,'RECAT_EU_C']=0
            df.at[index,'RECAT_EU_D']=1
            df.at[index,'RECAT_EU_E']=0
            df.at[index,'RECAT_EU_F']=0
            df.at[index,'RECAT_EU_G']=0

        elif RECAT_EU=='E':
            df.at[index,'RECAT_EU_A']=0
            df.at[index,'RECAT_EU_B']=0
            df.at[index,'RECAT_EU_C']=0
            df.at[index,'RECAT_EU_D']=0
            df.at[index,'RECAT_EU_E']=1
            df.at[index,'RECAT_EU_F']=0
            df.at[index,'RECAT_EU_G']=0

        elif RECAT_EU=='F':
            df.at[index,'RECAT_EU_A']=0
            df.at[index,'RECAT_EU_B']=0
            df.at[index,'RECAT_EU_C']=0
            df.at[index,'RECAT_EU_D']=0
            df.at[index,'RECAT_EU_E']=0
            df.at[index,'RECAT_EU_F']=1
            df.at[index,'RECAT_EU_G']=0

        elif RECAT_EU=='G':
            df.at[index,'RECAT_EU_A']=0
            df.at[index,'RECAT_EU_B']=0
            df.at[index,'RECAT_EU_C']=0
            df.at[index,'RECAT_EU_D']=0
            df.at[index,'RECAT_EU_E']=0
            df.at[index,'RECAT_EU_F']=0
            df.at[index,'RECAT_EU_G']=1

        elif RECAT_EU=='Z':
            df.at[index,'RECAT_EU_A']=0
            df.at[index,'RECAT_EU_B']=0
            df.at[index,'RECAT_EU_C']=0
            df.at[index,'RECAT_EU_D']=0
            df.at[index,'RECAT_EU_E']=0
            df.at[index,'RECAT_EU_F']=0
            df.at[index,'RECAT_EU_G']=0

        elif RECAT_EU==None:
            df.at[index,'RECAT_EU_A']=0
            df.at[index,'RECAT_EU_B']=0
            df.at[index,'RECAT_EU_C']=0
            df.at[index,'RECAT_EU_D']=0
            df.at[index,'RECAT_EU_E']=0
            df.at[index,'RECAT_EU_F']=0
            df.at[index,'RECAT_EU_G']=0
        else:
            df.at[index,'RECAT_EU_A']=0
            df.at[index,'RECAT_EU_B']=0
            df.at[index,'RECAT_EU_C']=0
            df.at[index,'RECAT_EU_D']=0
            df.at[index,'RECAT_EU_E']=0
            df.at[index,'RECAT_EU_F']=0
            df.at[index,'RECAT_EU_G']=0
        
    return df

In [59]:
Df_w_RECAT_EU= Icao_doc8643(df)

In [60]:
Df_w_RECAT_EU

,Unnamed: 0,Flight Number,Holding Time (minutes),Type Code,Time over fix,Big,Ock,Bov,Lam,WTC L,...,Departures delayIndex at -60,Arrivals numCancelled at -60,Arrivals delayIndex at -60,RECAT_EU_A,RECAT_EU_B,RECAT_EU_C,RECAT_EU_D,RECAT_EU_E,RECAT_EU_F,RECAT_EU_G
0,0,VIR450 _4170,0.0,B789,2023-04-01 03:31:29,1,0,0,0,0.0,...,0.00,0.0,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,118212,SHT7B _2891,0.0,A320,2023-10-06 13:18:29,0,0,1,0,0.0,...,1.39,4.0,0.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,118210,BAW6B _2728,0.0,A388,2023-10-06 13:14:29,0,0,1,0,0.0,...,1.44,4.0,0.00,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,118208,BAW80KA _3801,0.0,A21N,2023-10-06 13:10:59,0,0,1,0,0.0,...,1.44,4.0,0.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,118207,BAW311 _1730,0.0,A320,2023-10-06 13:13:59,0,1,0,0,0.0,...,1.44,4.0,0.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222970,189629,BAW9EW _4148,42.5,B789,2024-02-08 07:59:59,0,0,1,0,0.0,...,0.00,0.0,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0
222971,189660,EIN154 _6999,43.0,A21N,2024-02-08 08:54:59,0,0,1,0,0.0,...,0.89,0.0,0.03,0.0,0.0,0.0,1.0,0.0,0.0,0.0
222972,189641,VIR198 _3567,44.0,A333,2024-02-08 08:20:29,0,1,0,0,0.0,...,0.69,0.0,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0
222973,131120,AAL20 _9172,45.0,B77W,2023-10-31 05:01:29,0,1,0,0,0.0,...,0.00,0.0,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0
222974,200163,SVA119 _7292,70.0,B77W,2024-02-25 05:50:59,0,0,0,1,0.0,...,0.00,0.0,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [61]:
count_of_ones = (Df_w_RECAT_EU["RECAT_EU_A"] == 1).sum()
print(count_of_ones)

7258

In [62]:
unique_type_codes = doc8643at["RECAT_EU"].unique()
print(unique_type_codes)

['G' 'E' 'F' 'D' None 'C' 'B' 'A' 'Z']

In [63]:
Df_w_RECAT_EU.to_csv('EGLL_2023-04-01_00-00_till_2024-03-31_23-30_cleaned_RECAT.csv')

In [1]:
import pandas as pd

Df_w_RECAT_EU=pd.read_csv("EGLL_2023-04-01_00-00_till_2024-03-31_23-30_cleaned_RECAT.csv")

# Drop unnamed columns
Df_w_RECAT_EU = Df_w_RECAT_EU.loc[:, ~Df_w_RECAT_EU.columns.str.contains('^Unnamed')]

Df_w_RECAT_EU

,Flight Number,Holding Time (minutes),Type Code,Time over fix,Big,Ock,Bov,Lam,WTC L,WTC M,...,Departures delayIndex at -60,Arrivals numCancelled at -60,Arrivals delayIndex at -60,RECAT_EU_A,RECAT_EU_B,RECAT_EU_C,RECAT_EU_D,RECAT_EU_E,RECAT_EU_F,RECAT_EU_G
0,VIR450 _4170,0.0,B789,2023-04-01 03:31:29,1,0,0,0,0.0,0.0,...,0.00,0.0,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,SHT7B _2891,0.0,A320,2023-10-06 13:18:29,0,0,1,0,0.0,1.0,...,1.39,4.0,0.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,BAW6B _2728,0.0,A388,2023-10-06 13:14:29,0,0,1,0,0.0,0.0,...,1.44,4.0,0.00,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,BAW80KA _3801,0.0,A21N,2023-10-06 13:10:59,0,0,1,0,0.0,1.0,...,1.44,4.0,0.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,BAW311 _1730,0.0,A320,2023-10-06 13:13:59,0,1,0,0,0.0,1.0,...,1.44,4.0,0.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222970,BAW9EW _4148,42.5,B789,2024-02-08 07:59:59,0,0,1,0,0.0,0.0,...,0.00,0.0,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0
222971,EIN154 _6999,43.0,A21N,2024-02-08 08:54:59,0,0,1,0,0.0,1.0,...,0.89,0.0,0.03,0.0,0.0,0.0,1.0,0.0,0.0,0.0
222972,VIR198 _3567,44.0,A333,2024-02-08 08:20:29,0,1,0,0,0.0,0.0,...,0.69,0.0,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0
222973,AAL20 _9172,45.0,B77W,2023-10-31 05:01:29,0,1,0,0,0.0,0.0,...,0.00,0.0,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0
222974,SVA119 _7292,70.0,B77W,2024-02-25 05:50:59,0,0,0,1,0.0,0.0,...,0.00,0.0,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [2]:
Df_w_RECAT_EU.columns

Index(['Flight Number', 'Holding Time (minutes)', 'Type Code', 'Time over fix',
       'Big', 'Ock', 'Bov', 'Lam', 'WTC L', 'WTC M', 'WTC H', 'WTC J',
       'Engine Jet', 'Engine Turboprop/shaft', 'TimeStamp', 'Ceiling at -0',
       'Wind at -0', 'Precip at -0', 'Freezing at -0', 'Phenomena at -0',
       'Wind Direction at -0', 'Wind Speed at -0', 'Ceiling at -30',
       'Wind at -30', 'Precip at -30', 'Freezing at -30', 'Phenomena at -30',
       'Wind Direction at -30', 'Wind Speed at -30', 'Ceiling at -60',
       'Wind at -60', 'Precip at -60', 'Freezing at -60', 'Phenomena at -60',
       'Wind Direction at -60', 'Wind Speed at -60', 'day', 'month', 'year',
       'hour', 'minute', 'day_of_week', 'Day_0', 'Day_1', 'Day_2', 'Day_3',
       'Day_4', 'Day_5', 'Day_6', 'Decimal Hours -0', 'Decimal Hours -30',
       'Decimal Hours -60', 'Time leaving fix', 'Holding flights at -0',
       'Holding flights at -30', 'Holding flights at -60', 'Last Timestamp',
       'Last Track', 'Last Latitude', 'Runway 09L', 'Runway 09R', 'Runway 27L',
       'Runway 27R', 'Crosswind Component at -0', 'Headwind Component at -0',
       'Crosswind Component at -30', 'Headwind Component at -30',
       'Crosswind Component at -60', 'Headwind Component at -60',
       'No of Landings 1HR at -0', 'No of Landings 1HR at -30',
       'No of Landings 1HR at -60', 'Ground Speed at -0', 'Track at -0',
       'Altitude at -0', 'Ground Speed at -30', 'Track at -30',
       'Altitude at -30', 'Ground Speed at -60', 'Track at -60',
       'Altitude at -60', 'Departures delayIndex at -0',
       'Arrivals numCancelled at -0', 'Arrivals delayIndex at -0',
       'Departures delayIndex at -30', 'Arrivals numCancelled at -30',
       'Arrivals delayIndex at -30', 'Departures delayIndex at -60',
       'Arrivals numCancelled at -60', 'Arrivals delayIndex at -60',
       'RECAT_EU_A', 'RECAT_EU_B', 'RECAT_EU_C', 'RECAT_EU_D', 'RECAT_EU_E',
       'RECAT_EU_F', 'RECAT_EU_G'],
      dtype='object')

In [3]:
import pandas as pd


# 1) Create a reference DataFrame of TimeStamp + Runway columns, rename TimeStamp -> ref_time
runway_df = (
    Df_w_RECAT_EU[['Last Timestamp', 'Runway 09L', 'Runway 09R', 'Runway 27L', 'Runway 27R']]
    #.rename(columns={'TimeStamp': 'ref_time'})
    .sort_values('Last Timestamp')
)

runway_df['Last Timestamp'] = pd.to_datetime(
    runway_df['Last Timestamp'], 
    format='%Y-%m-%d %H:%M:%S'
)

Df_w_RECAT_EU['TimeStamp'] = pd.to_datetime(
    Df_w_RECAT_EU['TimeStamp'], 
    format='%Y-%m-%d %H:%M:%S'
)

Df_w_RECAT_EU['TimeStamp_minus_30min'] = Df_w_RECAT_EU['TimeStamp'] - pd.Timedelta(minutes=30)
Df_w_RECAT_EU['TimeStamp_minus_60min'] = Df_w_RECAT_EU['TimeStamp'] - pd.Timedelta(minutes=60)

#runway_df['ref_time_minus_60min'] = runway_df['ref_time'] - pd.Timedelta(minutes=60)


# 2) Sort your main DataFrame by the 'Last Timestamp' for merge_asof
#main_df = Df_w_RECAT_EU.sort_values('Last Timestamp').copy()

In [4]:
Df_w_RECAT_EU

,Flight Number,Holding Time (minutes),Type Code,Time over fix,Big,Ock,Bov,Lam,WTC L,WTC M,...,Arrivals delayIndex at -60,RECAT_EU_A,RECAT_EU_B,RECAT_EU_C,RECAT_EU_D,RECAT_EU_E,RECAT_EU_F,RECAT_EU_G,TimeStamp_minus_30min,TimeStamp_minus_60min
0,VIR450 _4170,0.0,B789,2023-04-01 03:31:29,1,0,0,0,0.0,0.0,...,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2023-04-01 02:50:59,2023-04-01 02:20:59
1,SHT7B _2891,0.0,A320,2023-10-06 13:18:29,0,0,1,0,0.0,1.0,...,0.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2023-10-06 12:48:29,2023-10-06 12:18:29
2,BAW6B _2728,0.0,A388,2023-10-06 13:14:29,0,0,1,0,0.0,0.0,...,0.00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2023-10-06 12:44:29,2023-10-06 12:14:29
3,BAW80KA _3801,0.0,A21N,2023-10-06 13:10:59,0,0,1,0,0.0,1.0,...,0.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2023-10-06 12:40:59,2023-10-06 12:10:59
4,BAW311 _1730,0.0,A320,2023-10-06 13:13:59,0,1,0,0,0.0,1.0,...,0.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2023-10-06 12:40:59,2023-10-06 12:10:59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222970,BAW9EW _4148,42.5,B789,2024-02-08 07:59:59,0,0,1,0,0.0,0.0,...,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2024-02-08 07:29:59,2024-02-08 06:59:59
222971,EIN154 _6999,43.0,A21N,2024-02-08 08:54:59,0,0,1,0,0.0,1.0,...,0.03,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2024-02-08 08:24:59,2024-02-08 07:54:59
222972,VIR198 _3567,44.0,A333,2024-02-08 08:20:29,0,1,0,0,0.0,0.0,...,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2024-02-08 07:46:59,2024-02-08 07:16:59
222973,AAL20 _9172,45.0,B77W,2023-10-31 05:01:29,0,1,0,0,0.0,0.0,...,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2023-10-31 04:29:29,2023-10-31 03:59:29
222974,SVA119 _7292,70.0,B77W,2024-02-25 05:50:59,0,0,0,1,0.0,0.0,...,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2024-02-25 05:13:29,2024-02-25 04:43:29

In [5]:
runway_df

            Last Timestamp  Runway 09L  Runway 09R  Runway 27L  Runway 27R
0      2023-04-01 03:39:59         0.0         0.0         0.0         1.0
96704  2023-04-01 04:11:29         0.0         0.0         0.0         1.0
96698  2023-04-01 04:16:59         0.0         0.0         0.0         1.0
96703  2023-04-01 04:20:29         0.0         0.0         0.0         1.0
96696  2023-04-01 04:30:29         0.0         0.0         0.0         1.0
...                    ...         ...         ...         ...         ...
47562  2024-03-31 21:32:59         1.0         0.0         0.0         0.0
187858 2024-03-31 21:34:29         1.0         0.0         0.0         0.0
145101 2024-03-31 21:36:59         1.0         0.0         0.0         0.0
151548 2024-03-31 21:41:59         1.0         0.0         0.0         0.0
156209 2024-03-31 21:48:29         1.0         0.0         0.0         0.0

[222975 rows x 5 columns]

In [6]:
# 3) Merge asof: left_on = 'Last Timestamp', right_on = 'ref_time'
#    direction='nearest' ensures we pick the closest match in time
Df_w_RECAT_EU=Df_w_RECAT_EU.sort_values('TimeStamp_minus_30min')

merged_df = pd.merge_asof(
    Df_w_RECAT_EU, 
    runway_df, 
    left_on='TimeStamp_minus_30min', 
    right_on='Last Timestamp',
    direction='nearest',
    suffixes=('', ' predicted at -30')  # We'll keep a suffix for the 'ref_time' DataFrame
)


# Now merged_df contains the original columns plus the four newly added "Actual Runway ..." columns.

In [7]:
merged_df=merged_df.drop(columns=['TimeStamp_minus_30min','Last Timestamp predicted at -30'])
Df_w_RECAT_EU=merged_df
Df_w_RECAT_EU

,Flight Number,Holding Time (minutes),Type Code,Time over fix,Big,Ock,Bov,Lam,WTC L,WTC M,...,RECAT_EU_C,RECAT_EU_D,RECAT_EU_E,RECAT_EU_F,RECAT_EU_G,TimeStamp_minus_60min,Runway 09L predicted at -30,Runway 09R predicted at -30,Runway 27L predicted at -30,Runway 27R predicted at -30
0,VIR450 _4170,0.0,B789,2023-04-01 03:31:29,1,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2023-04-01 02:20:59,0.0,0.0,0.0,1.0
1,BAW074 _2949,0.0,B77W,2023-04-01 03:58:29,0,1,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2023-04-01 02:54:59,0.0,0.0,0.0,1.0
2,BAW124 _1015,0.0,B772,2023-04-01 04:08:59,0,0,0,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2023-04-01 03:00:59,0.0,0.0,0.0,1.0
3,CPA251 _7192,0.0,B77W,2023-04-01 04:11:29,0,0,0,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2023-04-01 03:03:29,0.0,0.0,0.0,1.0
4,BAW58L _1080,0.0,B772,2023-04-01 04:22:29,1,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2023-04-01 03:10:59,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222970,BAW49TA _2662,6.5,A320,2024-03-31 21:23:59,0,0,1,0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,2024-03-31 20:09:59,1.0,0.0,0.0,0.0
222971,BAW64VC _2697,7.0,A319,2024-03-31 21:26:59,0,0,1,0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,2024-03-31 20:13:59,1.0,0.0,0.0,0.0
222972,BAW597C _2185,5.0,A320,2024-03-31 21:35:29,0,0,1,0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,2024-03-31 20:18:29,1.0,0.0,0.0,0.0
222973,BAW900A _2227,4.5,A320,2024-03-31 21:31:59,0,0,1,0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,2024-03-31 20:26:29,1.0,0.0,0.0,0.0
222974,TAP66JC _7201,5.0,A320,2024-03-31 21:42:59,0,0,1,0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,2024-03-31 20:37:59,1.0,0.0,0.0,0.0

In [8]:
# 3) Merge asof: left_on = 'Last Timestamp', right_on = 'ref_time'
#    direction='nearest' ensures we pick the closest match in time
Df_w_RECAT_EU=Df_w_RECAT_EU.sort_values('TimeStamp_minus_60min')

merged_df = pd.merge_asof(
    Df_w_RECAT_EU, 
    runway_df, 
    left_on='TimeStamp_minus_60min', 
    right_on='Last Timestamp',
    direction='nearest',
    suffixes=('', ' predicted at -60')  # We'll keep a suffix for the 'ref_time' DataFrame
)


# Now merged_df contains the original columns plus the four newly added "Actual Runway ..." columns.

In [9]:
merged_df=merged_df.drop(columns=['TimeStamp_minus_60min','Last Timestamp predicted at -60'])
Df_w_RECAT_EU=merged_df
Df_w_RECAT_EU

,Flight Number,Holding Time (minutes),Type Code,Time over fix,Big,Ock,Bov,Lam,WTC L,WTC M,...,RECAT_EU_F,RECAT_EU_G,Runway 09L predicted at -30,Runway 09R predicted at -30,Runway 27L predicted at -30,Runway 27R predicted at -30,Runway 09L predicted at -60,Runway 09R predicted at -60,Runway 27L predicted at -60,Runway 27R predicted at -60
0,VIR450 _4170,0.0,B789,2023-04-01 03:31:29,1,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,BAW074 _2949,0.0,B77W,2023-04-01 03:58:29,0,1,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2,BAW124 _1015,0.0,B772,2023-04-01 04:08:59,0,0,0,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,CPA251 _7192,0.0,B77W,2023-04-01 04:11:29,0,0,0,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,BAW58L _1080,0.0,B772,2023-04-01 04:22:29,1,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222970,BAW49TA _2662,6.5,A320,2024-03-31 21:23:59,0,0,1,0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
222971,BAW64VC _2697,7.0,A319,2024-03-31 21:26:59,0,0,1,0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
222972,BAW597C _2185,5.0,A320,2024-03-31 21:35:29,0,0,1,0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
222973,BAW900A _2227,4.5,A320,2024-03-31 21:31:59,0,0,1,0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
222974,TAP66JC _7201,5.0,A320,2024-03-31 21:42:59,0,0,1,0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [10]:
Df_w_RECAT_EU.to_csv('EGLL_2023-04-01_00-00_till_2024-03-31_23-30_cleaned_RECAT_PredRunway.csv')